version: '3.1'

services:

  db:
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_DB: drive
      POSTGRES_USER: mini-drive
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:5050"