version: '3.1'

services:

  api:
    build:
      context: ../../
      dockerfile: docker/prod/dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: drive
      POSTGRES_USER: mini-drive
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"