spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://db:5432/drive
    username: mini-drive
    password: password
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:liquibase/changelog/main-changelog.yaml
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB

server:
  port: 8080

app:
  jwt:
    secret: )H=#T@#[]HdPDMNqNMCMVS_usIr~_0Si87Zys562Sw~TAj$JKlx!]eYK.57ld#'W
    validityTimeInSeconds: 86400
  fileStorage:
    rootDirAbsolutePath: "C:\\MiniDriveStorage"
    tempDirName: ".temp"

logging:
  level:
    root: INFO
    com.n3lx.minidrive: INFO