spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/drive
    username: mini-drive
    password: password
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none