app:
  jwt:
    secret: )H=#T@#[]HdPDMNqNMCMVS_usIr~_0Si87Zys562Sw~TAj$JKlx!]eYK.57ld#'W
    validityTimeInSeconds: 600
  security:
    password:
      minLength: 8
      maxLength: 32

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/drive
    username: mini-drive
    password: password
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:liquibase/changelog/main-changelog.yaml

logging:
  level:
    root: INFO
    com.n3lx.minidrive: DEBUG